const Tether = artifacts.require('Tether');
const RWD = artifacts.require('RWD');
const DecentralBank = artifacts.require('DecentralBank');

// deployer: provided by the truffle
// network: network name, id and other network info defined in the configue file
// accounts: all the account inside the chain
module.exports = async function (deployer, network, accounts) {
    await deployer.deploy(Tether);
    // deployed is not from the ABI(generated by compliler 'solc'), it is part of the truffle framework
    //and Tether is not the contract, it is the contract abstraction provided by truffle
    const tether= await Tether.deployed();

    await deployer.deploy(RWD);

    const rwd=await RWD.deployed();

    await deployer.deploy(DecentralBank, rwd.address, tether.address);

    //1m
    await rwd.transfer(decentralBank.address, '1000000000000000000000000');
    //10
    await tether.transfer(accounts[1],        '10000000000000000000');

};
 